### ISSUE TITLE
Bug Report: exists may returns random result on a sharded table

### ISSUE THREAD

**Issue by zengmin-wish** [vitessio/vitess#10144]
### Overview of the Issue

We found an issue with exists : I can't provide the exact query we use, but for the query like 
```
select exists(select * from foo where some_field=some_value)
```
here foo is in a sharded keyspace, it seems if the inner query has result in one shard but have no result in another shard, then the outer query will return a random 0 or 1.  Not sure if it is related, but for our particular query, the table is sharded on the field 'some_field', so if Vitess is smart enough, it doesn't need to send the query to all the shard. 
We tried using gen4 planner, got the same result.

### Reproduction Steps

See description.

### Binary Version

```sh
v13.0.0
```

### Operating System and Environment details

```sh
# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by frouioui** [comment]
Hello @zengmin-wish, we encountered this issue in the past (https://github.com/vitessio/vitess/issues/9900). We fixed it on `main` and on `v13.0.1`. I see that you are running on `v13.0.0`, do you mind upgrading to `v13.0.1` and letting us know if that solves your issue?

**Comment by GuptaManan100** [comment]
Hello @zengmin-wish, me and @systay were looking at this bug today, and we can confirm that this is an issue in all the three `v13.0.0`, `v13.0.1` and `main`. The draft PR for the fix is here - https://github.com/vitessio/vitess/pull/10152

**Comment by systay** [comment]
this issue is still not fixed for V3, and it needs to be backported. opening this again until that is done
