### ISSUE TITLE
Bug Report: Error aplying `post_copy_action` on MoveTables workflow

### ISSUE THREAD

**Issue by iagoalonsomrf** [vitessio/vitess#18424]
### Overview of the Issue

Right after starting a MoveTables workflow, I get the following error:

```text
id=1 on rdb_dst/new-301: Status: Error. terminal error: Duplicate entry '1-tnt_properties' for key 'post_copy_action.vrepl_id' (errno 1062) (sqlstate 23000) during query: insert into _vt.post_copy_action(vrepl_id, table_name, action)
        values(1, 'tnt_properties', convert('{"type":1,"task":"alter table rdb.tnt_properties add key index2 (tnt_id, property)"}' using utf8mb4)).
```

I am using Vitess 22.0 with Docker (`vitess/<component>:v22.0.0-bookworm`) and MySQL 8.0 (`percona/percona-server:8.0.42-33.1`).

I am using `MoveTables` to migrate from `rdb_src` to `rdb_dst` keyspaces, using `rdb` as the database (with `--init_db_name_override rdb` in the vttablets).

I made sure that if I cancelled the workflow I truncated the `_vt` tables before starting again.

In the `Log Fragments` section you can see the output of the `MoveTables show` command.

### Reproduction Steps

I am able to replicate the issue with this schema:

```sql
CREATE DATABASE rdb;
USE rdb;

CREATE TABLE `tnts` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(128) DEFAULT NULL,
  `country` varchar(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tnt_properties` (
  `id` int NOT NULL AUTO_INCREMENT,
  `tnt_id` int DEFAULT NULL,
  `property` varchar(128) DEFAULT NULL,
  `value` varchar(2048) DEFAULT NULL,
  `source` varchar(45) DEFAULT NULL,
  `int_value` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index2` (`tnt_id`,`property`),
  CONSTRAINT `fk_tnt_properties_1` FOREIGN KEY (`tnt_id`) REFERENCES `tnts` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO tnts(id, name, country) VALUES(114, 'Test TNT', 'US');
INSERT INTO tnt_properties(id, tnt_id, property, value, source, int_value) VALUES(556, 114, 'city', 'New York', NULL, NULL);
```

The workflow is created like so:

```shell
vtctldclient MoveTables --target-keyspace rdb_dst --workflow rdb2vitess create --source-keyspace rdb_src --all-tables --cells old --tablet-types "primary"
```

### Binary Version

```sh
$ vttablet --version
vttablet version Version: 22.0.0 (Git revision b1922e25d516cac6d02e23f2bfab25a581837f00 branch 'HEAD') built on Tue Apr 29 13:05:41 UTC 2025 by vitess@buildkitsandbox using go1.24.2 linux/amd64



vtctld --version
vtctld version Version: 22.0.0 (Git revision b1922e25d516cac6d02e23f2bfab25a581837f00 branch 'HEAD') built on Tue Apr 29 13:05:41 UTC 2025 by vitess@buildkitsandbox using go1.24.2 linux/amd64
```

### Operating System and Environment details

```sh
Using Docker on bare metal
```

### Log Fragments

```sh
$ vtctldclient MoveTables --target-keyspace rdb_dst --workflow migration show
{
  "workflows": [
    {
      "name": "migration",
      "source": {
        "keyspace": "rdb_src",
        "shards": [
          "0"
        ]
      },
      "target": {
        "keyspace": "rdb_dst",
        "shards": [
          "0"
        ]
      },
      "max_v_replication_lag": "0",
      "shard_streams": {
        "0/gra-new-0000000301": {
          "streams": [
            {
              "id": "1",
              "shard": "0",
              "tablet": {
                "cell": "gra-new",
                "uid": 301
              },
              "binlog_source": {
                "keyspace": "rdb_src",
                "shard": "0",
                "tablet_type": "UNKNOWN",
                "key_range": null,
                "tables": [],
                "filter": {
                  "rules": [
                    {
                      "match": "tnt_properties",
                      "filter": "select * from tnt_properties",
                      "convert_enum_to_text": {},
                      "convert_charset": {},
                      "source_unique_key_columns": "",
                      "target_unique_key_columns": "",
                      "source_unique_key_target_columns": "",
                      "convert_int_to_enum": {},
                      "force_unique_key": ""
                    },
                    {
                      "match": "tnts",
                      "filter": "select * from tnts",
                      "convert_enum_to_text": {},
                      "convert_charset": {},
                      "source_unique_key_columns": "",
                      "target_unique_key_columns": "",
                      "source_unique_key_target_columns": "",
                      "convert_int_to_enum": {},
                      "force_unique_key": ""
                    }
                  ],
                  "field_event_mode": "ERR_ON_MISMATCH",
                  "workflow_type": "0",
                  "workflow_name": ""
                },
                "on_ddl": "IGNORE",
                "external_mysql": "",
                "stop_after_copy": false,
                "external_cluster": "",
                "source_time_zone": "",
                "target_time_zone": ""
              },
              "position": "",
              "stop_position": "",
              "state": "Error",
              "db_name": "rdb",
              "transaction_timestamp": {
                "seconds": "0",
                "nanoseconds": 0
              },
              "time_updated": {
                "seconds": "20250707083838",
                "nanoseconds": 0
              },
              "message": "terminal error: Duplicate entry '1-tnt_properties' for key 'post_copy_action.vrepl_id' (errno 1062) (sqlstate 23000) during query: insert into _vt.post_copy_action(vrepl_id, table_name, action)\n\tvalues(1, 'tnt_properties', convert('{\"type\":1,\"task\":\"alter table rdb.tnt_properties add key index2 (tnt_id, property)\"}' using utf8mb4))",
              "copy_states": [],
              "logs": [
                {
                  "id": "1",
                  "stream_id": "1",
                  "type": "Stream Created",
                  "state": "Stopped",
                  "created_at": {
                    "seconds": "1751877518",
                    "nanoseconds": 0
                  },
                  "updated_at": {
                    "seconds": "1751877518",
                    "nanoseconds": 0
                  },
                  "message": "{\"cell\":\"old\",\"component_throttled\":\"\",\"db_name\":\"rdb\",\"defer_secondary_keys\":\"1\",\"id\":\"1\",\"max_replication_lag\":\"0\",\"max_tps\":\"0\",\"options\":\"{\\\"sharded_auto_increment_handling\\\": 1}\",\"pos\":\"\",\"reason_throttled\":\"\",\"rows_copied\":\"0\",\"source\":\"keyspace:\\\"rdb_src\\\" shard:\\\"0\\\" filter:{rules:{match:\\\"tnt_properties\\\" filter:\\\"select * from tnt_properties\\\"} rules:{match:\\\"tnts\\\" filter:\\\"select * from tnts\\\"}}\",\"state\":\"Stopped\",\"tablet_types\":\"in_order:primary\",\"tags\":\"\",\"time_heartbeat\":\"0\",\"time_throttled\":\"0\",\"time_updated\":\"20250707083838\",\"transaction_timestamp\":\"0\",\"workflow\":\"migration\",\"workflow_sub_type\":\"0\",\"workflow_type\":\"1\"}",
                  "count": "1"
                },
                {
                  "id": "2",
                  "stream_id": "1",
                  "type": "State Changed",
                  "state": "Running",
                  "created_at": {
                    "seconds": "1751877518",
                    "nanoseconds": 0
                  },
                  "updated_at": {
                    "seconds": "1751877518",
                    "nanoseconds": 0
                  },
                  "message": "",
                  "count": "1"
                },
                {
                  "id": "5",
                  "stream_id": "1",
                  "type": "Message",
                  "state": "Copying",
                  "created_at": {
                    "seconds": "1751877518",
                    "nanoseconds": 0
                  },
                  "updated_at": {
                    "seconds": "1751877518",
                    "nanoseconds": 0
                  },
                  "message": "Cannot drop index 'index2': needed in a foreign key constraint (errno 1553) (sqlstate HY000) during query: alter table rdb.tnt_properties drop key index2",
                  "count": "1"
                },
                {
                  "id": "8",
                  "stream_id": "1",
                  "type": "Message",
                  "state": "Copying",
                  "created_at": {
                    "seconds": "1751877523",
                    "nanoseconds": 0
                  },
                  "updated_at": {
                    "seconds": "1751877523",
                    "nanoseconds": 0
                  },
                  "message": "Duplicate entry '1-tnt_properties' for key 'post_copy_action.vrepl_id' (errno 1062) (sqlstate 23000) during query: insert into _vt.post_copy_action(vrepl_id, table_name, action)\n\tvalues(1, 'tnt_properties', convert('{\"type\":1,\"task\":\"alter table rdb.tnt_properties add key index2 (tnt_id, property)\"}' using utf8mb4))",
                  "count": "1"
                },
                {
                  "id": "9",
                  "stream_id": "1",
                  "type": "State Changed",
                  "state": "Error",
                  "created_at": {
                    "seconds": "1751877523",
                    "nanoseconds": 0
                  },
                  "updated_at": {
                    "seconds": "1751877523",
                    "nanoseconds": 0
                  },
                  "message": "terminal error: Duplicate entry '1-tnt_properties' for key 'post_copy_action.vrepl_id' (errno 1062) (sqlstate 23000) during query: insert into _vt.post_copy_action(vrepl_id, table_name, action)\n\tvalues(1, 'tnt_properties', convert('{\"type\":1,\"task\":\"alter table rdb.tnt_properties add key index2 (tnt_id, property)\"}' using utf8mb4))",
                  "count": "1"
                }
              ],
              "log_fetch_error": "",
              "tags": [
                ""
              ],
              "rows_copied": "0",
              "throttler_status": {
                "component_throttled": "",
                "time_throttled": {
                  "seconds": "0",
                  "nanoseconds": 0
                }
              },
              "tablet_types": [
                "PRIMARY"
              ],
              "tablet_selection_preference": "ANY",
              "cells": [
                "old"
              ]
            }
          ],
          "tablet_controls": [
            {
              "tablet_type": "PRIMARY",
              "cells": [],
              "denied_tables": [
                "tnt_properties",
                "tnts"
              ],
              "frozen": false
            }
          ],
          "is_primary_serving": true
        }
      },
      "workflow_type": "MoveTables",
      "workflow_sub_type": "None",
      "max_v_replication_transaction_lag": "0",
      "defer_secondary_keys": true,
      "options": {
        "tenant_id": "",
        "sharded_auto_increment_handling": "REMOVE",
        "shards": [],
        "config": {},
        "global_keyspace": ""
      }
    }
  ]
}
```

**Comment by mattlord-istari** [comment]
Here is a repeatable test case:
```
git checkout main && make build

cd examples/local

./101_initial_cluster.sh

vtctldclient ApplySchema --sql 'CREATE TABLE `tnts` ( `id` int NOT NULL AUTO_INCREMENT, `name` varchar(128) DEFAULT NULL, `country` varchar(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `name` (`name`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci; CREATE TABLE `tnt_properties` ( `id` int NOT NUL
L AUTO_INCREMENT, `tnt_id` int DEFAULT NULL, `property` varchar(128) DEFAULT NULL, `value` varchar(2048) DEFAULT NULL, `source` varchar(45) DEFAULT NULL, `int_value` int DEFAULT NULL, PRIMARY KEY (`id`), KEY `index2` (`tnt_id`,`property`), CONSTRAINT `fk_tnt_properties_1` FOREIGN KEY (`tnt_id`) REFERENCES `tnts` (`id`
) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;' commerce

mysql -e "INSERT INTO tnts(id, name, country) VALUES(114, 'Test TNT', 'US'); INSERT INTO tnt_properties(id, tnt_id, property, value, source, int_value) VALUES(556, 114, 'city', 'New York', NULL, NULL);"

./201_customer_tablets.sh

vtctldclient MoveTables --workflow commerce2customer --target-keyspace customer create --source-keyspace commerce --all-tables

vtctldclient MoveTables --workflow commerce2customer --target-keyspace customer status
```

And if you look at the workflow's status:
```
❯ vtctldclient MoveTables --workflow commerce2customer --target-keyspace customer status
The following vreplication streams exist for workflow customer.commerce2customer:

id=1 on customer/zone1-200: Status: Error. terminal error: Duplicate entry '1-tnt_properties' for key 'post_copy_action.vrepl_id' (errno 1062) (sqlstate 23000) during query: insert into _vt.post_copy_action(vrepl_id, table_name, action)
        values(1, 'tnt_properties', convert('{"type":1,"task":"alter table vt_customer.tnt_properties add key index2 (tnt_id, property)"}' using utf8mb4)).

Traffic State: Reads Not Switched. Writes Not Switched
```

**Comment by mattlord-istari** [comment]
This works fine (removing the FK constraint):
```
./101_initial_cluster.sh

vtctldclient ApplySchema --sql 'CREATE TABLE `tnts` ( `id` int NOT NULL AUTO_INCREMENT, `name` varchar(128) DEFAULT NULL, `country` varchar(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `name` (`name`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci; CREATE TABLE `tnt_properties` ( `id` int NOT NUL
L AUTO_INCREMENT, `tnt_id` int DEFAULT NULL, `property` varchar(128) DEFAULT NULL, `value` varchar(2048) DEFAULT NULL, `source` varchar(45) DEFAULT NULL, `int_value` int DEFAULT NULL, PRIMARY KEY (`id`), KEY `index2` (`tnt_id`,`property`) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;' commerce

mysql -e "INSERT INTO tnts(id, name, country) VALUES(114, 'Test TNT', 'US'); INSERT INTO tnt_properties(id, tnt_id, property, value, source, int_value) VALUES(556, 114, 'city', 'New York', NULL, NULL);"

./201_customer_tablets.sh

vtctldclient MoveTables --workflow commerce2customer --target-keyspace customer create --source-keyspace commerce --all-tables

vtctldclient MoveTables --workflow commerce2customer --target-keyspace customer status
```

So it's something related to the FK constraint.

**Comment by mattlord-istari** [comment]
One of the shards in the user's case shows this error:
```
"Cannot drop index 'index2': needed in a foreign key constraint (errno 1553) (sqlstate HY000) during query: alter table rdb.tnt_properties drop key index2"
```

I bet the `ALTER TABLE DROP KEY` is failing on each shard with that same error, causing the workflow to go into the error state. It's then retried and we start the post copy action setup again on retry as the secondary index is still in place. But we still have the record in the `post_copy_action` from the previous attempt — thus the duplicate key error seen on the other shards.

**Comment by mattlord-istari** [comment]
Related to: https://github.com/vitessio/vitess/issues/14547

**Comment by mattlord-istari** [comment]
This is the same basic issue noted here: https://github.com/vitessio/vitess/issues/14547

And fixed in: https://github.com/vitessio/vitess/pull/14543

In this test case, with a FK constraint, you should use the `--atomic-copy` MoveTables flag to ensure that the data is correctly copied (when spanning multiple copy phase cycles). What's missing here is handling this case well with NOT using `--atomic-copy`.

**Comment by iagoalonsomrf** [comment]
After testing with the `--atomic-copy` flag, the workflow still failed with the following message:

```text
"message": "Cannot drop index 'index2': needed in a foreign key constraint (errno 1553) (sqlstate HY000) during query: alter table rdb.tnt_properties drop key index2",
```

However using `--atomic-copy --defer-secondary-keys=false` allowed the workflow to start sucessfully and I could see some data starting to get copied.

**Comment by mattlord** [comment]
OK, this has been triaged and confirmed. /cc @vitessio/vreplication
