### ISSUE TITLE
heartbeat table creation is not written to binlogs breaking replicas

### ISSUE THREAD

**Issue by sjmudd** [vitessio/vitess#3404]
Related to: https://github.com/youtube/vitess/pull/2746.

After creating a new keyspace by creating 3 empty tablets at the same time I notice that when I do `InitShardMaster` that replication is broken on the 2 replicas.

I'm using as part of my vttablet startup the following entry: `-heartbeat_enable`. The idea of the heartbeat is good and I want to use it.

Looking to see why there's breakage I see that the binlog for the master does NOT create the heartbeat table. The code seems to deliberately not write to the binlogs as can be seen here:

```
        statements := []string{
                sqlTurnoffBinlog,
                fmt.Sprintf(sqlCreateSidecarDB, w.dbName),
                fmt.Sprintf(sqlCreateHeartbeatTable, w.dbName),
        }
```

Nothing on the slave creates the table either so in the end you get a replication error of the type:
`Last_Error: Error executing row event: 'Table '_vt.heartbeat' doesn't exist'`.

Talking with bbeaudreault, the author of the original patch it looks like he does a backup after making one of the tablets a master. If you do this then the table will be in the copy used subsequently but I believe that there's no requirement to use a backup to create a new replica.

My suggestion would therefore be to remove the line: `sqlTurnoffBinlog` from the code to allow the table creation to be replicated and then immediately after replication is setup the table will exist on the other copies and the heartbeat mechanism will work fine. I assume this code is only sent when a tablet gets "promoted to be a master" and in any case the statements are replication safe. If the database or table already exists then nothing will change.

Thoughts and comments welcome.

**Comment by sjmudd** [comment]
So included proposed patch which for me fixes the problem.

**Comment by pivanof** [comment]
From my reading of the code I believe the idea is that the heartbeat table is always created by vttablet on startup, no matter if it's master or slave. And I agree with that idea, especially since it uses the dba account, it would be dangerous to use it with binlogging turned on. So now we need to understand why the table is not created on slaves for you. Do they have -heartbeat_enable flag as well? Or maybe the call to Init() on heartbeat.Writer is put in the wrong place (now it's in TabletServer.fullStart() )?

**Comment by sjmudd** [comment]
Again the example of building a new keyspace is to build several empty servers just applying the initial sql script to allow the vt_dba user to access the server.

So I built 3 such tablets. All of them have the the heartbeat enabled. They all come up as replica if I remember correctly (but not as a master) and the table is definitely not created on them. When running `InitShardMaster` to setup the replication topology I see in the binlogs that the heartbeat kicks in and I see "row update events" for the heartbeat table.  There's no visible creation of the heartbeat table in the binlogs of any box.  Immediately here I see that replication fails with the error indicated showing the table does not exist on the slave.

To me it seems problematic to not binlog the creation of a table you write to... This is not consistent.  So I think that the tablet writing the heartbeat should if it detects the tablet changes to be a master attempt to create the table if missing `CREATE TABLE IF NOT EXISTS ....`, and afterwards it is completely safe to send insert or update events.  This means that any servers created in the same state as the original master will pick up the create table when replication is setup (via `InitShardMaster -force`) and then will pick up changes to the table as normal.

As stated it seems to me that the reason this has not been seen before is that a backup made to a single tablet configured as a master will have the heartbeat table created so any copies of that will work fine. I was not building the new keyspace that way.

My specific startup of tablets does not startup mysqld which is done separately but it does have the following:

```
        $sudo_exec \
        $VTROOT/bin/vttablet \
                $TOPOLOGY_FLAGS \
                -log_dir $VTDATAROOT/tmp \
                -tablet-path $ALIAS \
                -tablet_hostname "$HOSTNAME" \
                -init_keyspace $KEYSPACE \
                -init_shard $SHARD \
                -init_tablet_type $TABLET_TYPE \
                -init_db_name_override $DBNAME \
                -mycnf_mysql_port $MYSQL_PORT \
                -health_check_interval 5s \
                -enable_semi_sync \
                -enable_replication_reporter \
                $enable_heartbeat \
                $backup_config \
                -binlog_use_v3_resharding_mode \
                -port $WEB_PORT \
                -enforce_strict_trans_tables=false \
                -grpc_port $GRPC_PORT \
                -grpc_max_message_size $GRPC_MAX_MESSAGE_SIZE \
                -service_map 'grpc-queryservice,grpc-tabletmanager,grpc-updatestream' \
                -pid_file $PIDFILE \
                -vtctld_addr http://${VTCTLD_HOST}:${VTCTLD_WEB_PORT}/ \
                $DBCONFIG_FLAGS \
                > $VTDATAROOT/$TABLET_DIR/vttablet.out 2>&1 &
```

and the heartbeat is enabled `-heartbeat_enable`. 

[ This is configurable as it's disabled on some replicas which talk to a production (not Vitess) setup and configured (for testing) as replicas. In that case the upstream master is not known to Vitess and so there's no heartbeat information to check. ]

You mention the table being created on master and slaves. Really? Why would you try to write to a replica/slave which is read-only? That doesn't make any sense and it won't work unless you have `super` which `vt_dba` does not have. The table creation is triggered in the writer on startup https://github.com/youtube/vitess/blob/master/go/vt/vttablet/heartbeat/writer.go#L158

The reader does not create the table.

What's not 100% clear to me is when a table changes from one type to another how that changes the heartbeat behaviour.

**Comment by pivanof** [comment]
vt_dba actually has SUPER privilege (at least Vitess code assumes that), and yes really, table is supposed to be created both on master and slaves, so that the heartbeat could be easily turned on on a running system. Table creation is triggered in the writer startup, which is supposed to be executed on every tablet independently from its type. Currently it's called from TabletServer.fullStart(). If you verified that the table is not created on any tablet in a newly built keyspace until InitShardMaster is called, then it means we don't call fullStart() in such situation, and thus it wasn't correct to put the call to Init() of the writer there. We have creation of other auxiliary tables done in here https://github.com/youtube/vitess/blob/master/go/vt/mysqlctl/metadata_tables.go#L70, and that might be a good place to create the heartbeat table as well, but I'm not sure a call to Init() of the writer will be appropriate there. Maybe it should be put somewhere else in TabletServer, where it will always be called on startup. bbeaudreault@, do you have any thoughts where this can go?

**Comment by bbeaudreault** [comment]
I was directed by @sougou to put this in `fullStart`, see https://github.com/youtube/vitess/pull/2746#issuecomment-292073093 and other references to "init" further down that review.

I'm open to it moving wherever it makes sense, but I don't think i'll have any bandwidth to work on that in the near future. If someone wants to submit a PR, someone else on our vitess team can try pulling it into our dev environment to ensure it didn't break our use-case.  cc @acharis @hmcgonig

**Comment by pivanof** [comment]
I guess then we need to wait for @sougou to tell us why he thought that fullStart() is called on each vttablet startup, but it isn't, and whether the call to Init() should be moved to a different place or the fix should be made to always call fullStart() on each vttablet startup.

**Comment by sougou** [comment]
I haven't read the full issue. So, I lack the context here. However, it should be ok to move the creation to a better location if fullStart is not the right place.

In the longer run, we should look at relying on creating such tables only on the master (with replication turned on). This is because vt_dba may not have the necessary `SUPER` privileges to write to replicas. For example, RDS will definitely not let us do such things. There also other deployments where users are unwilling to give vt_dba such privileges.

**Comment by sjmudd** [comment]
The  `vt_dba` user does have full privileges on the database so _can_ write to the replica even if it is `read_only`.  I'm not sure however when the write to the database takes place and see it is written by the `heartbeat.Writer` here: https://github.com/youtube/vitess/blob/master/go/vt/vttablet/heartbeat/writer.go#L158 where also the "initial row" is written. That makes sense though I still this think should be binlogged.  Also note the initial row is tablet specific. See `sqlInsertInitialRow`.

I still don't believe that the write happens on the slave: this would generate a row for a different tablet and thus leave multiple entries in the table which does not make sense to me. Also my experience with building the few empty tablets was to see the replication breakage. Only visible if I enable the heartbeat and the indication on the slave that the heartbeat table did not exist (on the slave).

@bbeaudreault would you be able to just try my patch and see if it breaks anything for you? (it's a one line change).
@sougou: what is the rationale for _not_  binlogging the table creation? That's something I don't understand. How can it make sense (ignoring Vitess) to update a table that you don't explicitly create? Anyone pulling in the binlogs of a new empty box will find the "stream" will not build a working server. That feels wrong to me.

So maybe I'm over labouring a point here. I'm only doing that as I can't see what I'm doing wrong building a new empty keyspace. it works without enabling the heartbeat but for me fails for the reasons explained.  I'm still not convinced from what I've read that I'm doing anything wrong so if I am please explain what I'm doing wrong and what I should do instead.

Thanks.

**Comment by sjmudd** [comment]
@sougou: context is for me replication breaks building a new keyspace with table not found error on the slave after running `InitShardMaster`. The table creation is not binlogged, apparently by design so does not get created on the replicas.

**Comment by alainjobart** [comment]
I think the underlying design concept is there are two ways to create a table in a replicated database:

1. create it on each server with binlogs off. Con: if you miss one tablet, you're hosed. The case you hit. Restarting vttablet on the slaves with heartbeat enabled might fix replication, as it would create the table then, and then replication can then resume? Not sure about that.

2. create it on the master with binlogs on, and let it replicate. Con: it's hard to find the right time to create that table. Which tablet do we create it on? It has to be the master, but when? Tablets start as replica, before they're initialized. So maybe after InitShardMaster we should create it, when we have the new master. But what about enabling heartbeat after the shard has been created and used, we can't run InitShardMaster again...

Now I'm not opposed to revisiting why we chose number 1. But it's not that we don't want to replicate the table creation statement, it's that it's hard to know when to issue it. It felt easier to check the table exists on each instance, and maybe create it with binlogs off, than to find the exact right time to do it.

Does that make more sense?

**Comment by pivanof** [comment]
Simon, you are not doing anything wrong, but Vitess behaves incorrectly not creating heartbeat table on the slaves. That should be fixed, but blindly turning on binlogging is not the correct fix. Binlogging should never be enabled for statements executed on the slaves, otherwise replication can easily break. And if you really want to binlog the table creation you should make sure that the table is created only on master and that it's done using vt_allwrite user, not vt_dba (i.e. the user that doesn't have SUPER). In fact I think your patch, Simon, allows replication to proceed after InitShardMaster in the initial keyspace setup, but I think it will break replication if you try reparents to different tablets after that.

And regarding the code: the fact that sqlInsertInitialRow inserts tablet's UID has confused me initially into thinking that there will be separate rows as well. But notice that the heartbeat table has only keyspaceShard in the primary key, so the table will always have only one row per shard. And strictly speaking this code inserting tablet's UID is really bad because it creates data drift between replicas (when it works and actually creates the table on slaves). And the only reason it has potential to work is because tablet UID is never read and nothing depends on it.

**Comment by sjmudd** [comment]
One thing that's still not clear to me is during reparenting how the new master gets it's heartbeat "initiated", but at the same time maintaining only a single row in the heartbeat table.

Outside of Vitess when I handle this the change to a new master triggers the old rows to be removed and then the new row to be created. This change is done explicitly. Also the insert is written as INSERT ON DUPLICATE KEY UPDATE as this ensures that if you have an empty table on a slave it will be populated correctly. This works in SBR but may not in RBR.

My feeling therefore is that the initialisation of the heartbeat possibly needs to be handled differently so that the process for a normal startup and the process for a reparent shares the same code and as it seems we agree that writing only takes place on the master.

**Comment by derekperkins** [comment]
@enisoc and I are running into this issue when installing a new cluster on Kubernetes with helm. There's an inherent race condition somewhere that causes ~50% of replicas to come up uninitialized.

**Comment by enisoc** [comment]
It looks like the heartbeat table is showing up on replicas, eventually. The problem is that there's no coordination between that and the start of replication. If replication wins the race, the SQL thread blocks.

We could coordinate better with replication if we set up the heartbeat in tabletmanager rather than tabletserver. For example, we could ensure the table is set up during InitMaster and InitSlave, or perhaps when we populate `local_metadata`. It also makes more sense to me conceptually for heartbeat to be a feature of tabletmanager (which manages healthchecks and replication) rather than tabletserver (which serves user queries).

What do you all think?

**Comment by alainjobart** [comment]
I agree it would be better in tabletmanager.

**Comment by pivanof** [comment]
I agree as well. Citing myself from my earlier comment (made on Nov, 22): "We have creation of other auxiliary tables done in here https://github.com/youtube/vitess/blob/master/go/vt/mysqlctl/metadata_tables.go#L70, and that might be a good place to create the heartbeat table as well, but I'm not sure a call to Init() of the writer will be appropriate there." That code I pointed to is called from ActionAgent.RestoreData() inside tabletmanager, and I think it's the most appropriate to create the heartbeat table. But call to Init() on the writer to the table might be more appropriate in tabletserver actually and be coupled with the tablet starting to serve master queries.

**Comment by sougou** [comment]
Closed via #6053
