### ISSUE TITLE
vtgate HealthCheck Tablet Cache incorrect information

### ISSUE THREAD

**Issue by grsmith-projects** [vitessio/vitess#8465]
Hello!

I've noticed that when there is a topology change, sometimes the `HealthCheck Tablet Cache`
data for vtgate becomes stale and it misreports TabletHealth.

I've been able to repro this a few times in a cluster that is:

1 x 2 shard keyspace, with 3 replicas each
1 x unsharded keyspace, with 3 replicas

There are 40 vtgate instances (2 cpu), we are pushing ~15k req/s with varying payload sizes and mix of different query plans.

to repro, I just kill any vttablet pod - there is a chance that some number of vtgate `HealthCheck Tablet Cache` will become stale.

I can determine this by vtgate having an entry for a tablet 1234, that is showing as a failed master -- but recently has been changed to a replica. The tablet ID will be the same for when it changes state between master/replica, but I think the pod IP changes.  The newly created tablet with a different IP will set itself healthy, but the old tablet will remain in the table as unhealthy for some reason (on a % of existing vtgate instances). The only way I've found to clear it is by restarting the vtgate pod. I've attached a screenshot.

![Screenshot from 2021-07-13 12-32-58](https://user-images.githubusercontent.com/1625735/125522557-ddaa7e94-c1c6-4cb9-b7e9-6fa50ebbf6b8.png)

The stale data shows the tablet alias as red, with an error message that says 

```(Code: CANCELED vttablet: rpc error: code = Canceled desc = context canceled )```

I found this in the logs which appears to correlate with the old IP address of the tablet showing a stale HealthCheck:

> [core] grpc: addrConn.createTransport failed to connect to {10.0.0.1:15999 10.0.0.1:15999 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 10.0.0.1:15999: operation was canceled". Reconnecting...

```/vt/bin/vtgate --version
Version: 12.0.0-SNAPSHOT (Git revision 9fa6ff4400 branch 'main') built on Thu Jul  8 18:16:08 UTC 2021 by vitess@buildkitsandbox using go1.16.5 linux/amd64
```

This is using kubernetes.

Thanks!

**Comment by mattlord** [comment]
Hi @grsmith-projects !

Thank you for reporting this.

I have not yet been able to repeat this when running loops like this which, AFAICT, are doing what you mention (using the [docker_local](https://vitess.io/docs/get-started/local-docker/) container):
```
mysql> show vitess_tablets;
+-------+----------+-------+------------+---------+------------------+--------------+----------------------+
| Cell  | Keyspace | Shard | TabletType | State   | Alias            | Hostname     | PrimaryTermStartTime |
+-------+----------+-------+------------+---------+------------------+--------------+----------------------+
| zone1 | commerce | 0     | PRIMARY    | SERVING | zone1-0000000100 | bad224d0ef67 | 2021-10-09T04:13:14Z |
| zone1 | commerce | 0     | REPLICA    | SERVING | zone1-0000000101 | bad224d0ef67 |                      |
| zone1 | commerce | 0     | RDONLY     | SERVING | zone1-0000000102 | bad224d0ef67 |                      |
+-------+----------+-------+------------+---------+------------------+--------------+----------------------+
3 rows in set (0.00 sec)

$ while true; do sleep .1; idsuffix=$((${RANDOM}%3)); kill -9 $(pgrep -f "vt_000000010${idsuffix}/vttablet.pid"); vttablet -topo_implementation etcd2 -topo_global_server_address localhost:2379 -topo_global_root /vitess/global -log_dir /vt/vtdataroot/tmp -tablet-path zone1-000000010${idsuffix} -tablet_hostname $(hostname) -init_keyspace commerce -init_shard 0 -init_tablet_type replica -port 1510${idsuffix} -grpc_port 1610${idsuffix}  -service_map grpc-queryservice,grpc-tabletmanager,grpc-updatestream -pid_file /vt/vtdataroot/vt_000000010${idsuffix}/vttablet.pid & mysql -e "show vitess_tablets"; if [[ $(mysql -BNe "show vitess_tablets" | wc -l) -gt 3 ]]; then echo -n "\n\nGot 'em\n\n"; break; fi; done

## OR

$ while true; do sleep .1; idsuffix=$((${RANDOM}%3)); vtctlclient TabletExternallyReparented zone1-10${idsuffix}; sleep .2; kill -9 $(pgrep -f "vt_000000010${idsuffix}/vttablet.pid"); vttablet -topo_implementation etcd2 -topo_global_server_address localhost:2379 -topo_global_root /vitess/global -log_dir /vt/vtdataroot/tmp -tablet-path zone1-000000010${idsuffix} -tablet_hostname $(hostname) -init_keyspace commerce -init_shard 0 -init_tablet_type replica -port 1510${idsuffix} -grpc_port 1610${idsuffix}  -service_map grpc-queryservice,grpc-tabletmanager,grpc-updatestream -pid_file /vt/vtdataroot/vt_000000010${idsuffix}/vttablet.pid & mysql -e "show vitess_tablets"; if [[ $(mysql -BNe "show vitess_tablets" | wc -l) -gt 3 ]]; then echo -n "\n\nGot 'em\n\n"; break; fi; done
```

So there's some piece of the puzzle that I'm missing here. If you do ever see this happen again, can you please save the output of this from one of the vtgate's that have the invalid `show vitess_tablets` output:
```
grep -I healthcheck /<path to>/vtgate.INFO
```

This will hopefully offer some clues that will allow us to track this down and fix it. Thanks again!

Matt

**Comment by derekperkins** [comment]
I can confirm that we see this too. Related to #8909, we've had to force kill a lot of tablets in the last couple weeks. 
Our clean shutdown does delete the tablet record as @deepthi suggested, but that doesn't happen on a force delete. I have seen the CANCELED state that @grsmith-projects posted. I have seen the master also have a replica record with the same tablet id. 

![image](https://user-images.githubusercontent.com/3588778/136646140-427a4895-7d4d-4093-af86-8657187cd3eb.png)

I'm running vtgate 10.0.1 and vttablet 11.0.1

**Comment by mattlord** [comment]
I'm going to close this for now as fixed via: https://github.com/vitessio/vitess/pull/9106

If I missed anything or anyone still seems to encounter the issue with this patch applied please let me know and we can re-open it. Thank you for the great issue!

**Comment by niv8** [comment]
Looks like this is still happening in Vitess 12 in k8s:

**vtctlclient listalltablets** output:
```
app-0579381204 bi - replica 10.244.0.14:15000 10.244.0.14:3306 [] <null>
app-1150396303 bi - primary 10.244.6.5:15000 10.244.6.5:3306 [] 2022-01-15T09:10:16Z
app-3029106754 bi - replica 10.244.3.11:15000 10.244.3.11:3306 [] <null>
app-4050924606 bi - replica 10.244.8.89:15000 10.244.8.89:3306 [] <null>
```

**show vitess_tablets** output:
```
+------+--------------+-------+------------+-------------+----------------+-------------+----------------------+
| Cell | Keyspace     | Shard | TabletType | State       | Alias          | Hostname    | PrimaryTermStartTime |
+------+--------------+-------+------------+-------------+----------------+-------------+----------------------+
| app  | bi           | -     | PRIMARY    | NOT_SERVING | app-3029106754 | 10.244.3.8  | 2022-01-15T08:53:59Z |
| app  | bi           | -     | PRIMARY    | SERVING     | app-1150396303 | 10.244.6.5  | 2022-01-15T09:10:16Z |
| app  | bi           | -     | REPLICA    | SERVING     | app-3029106754 | 10.244.3.11 |                      |
| app  | bi           | -     | REPLICA    | SERVING     | app-4050924606 | 10.244.8.89 |                      |
| app  | bi           | -     | REPLICA    | SERVING     | app-0579381204 | 10.244.0.14 |                      |
+------+--------------+-------+------------+-------------+----------------+-------------+----------------------+
```

**Comment by mattlord** [comment]
@niv8 no, unfortunately restarting the vtgate is the only way to get rid of them.

**Comment by vkovacik** [comment]
@mattlord Your comment suggests that this issue is not fixed even though the issue has been closed. Is there another issue that is a follow up of `restarting the vtgate is the only way to get rid of them` ?

**Comment by mattlord** [comment]
Hi @vkovacik!

> @mattlord Your comment suggests that this issue is not fixed even though the issue has been closed. Is there another issue that is a follow up of `restarting the vtgate is the only way to get rid of them` ?

I was answering a user encountering the issue in a Vitess 12.0 cluster. The issue was fixed in main/13.0 but was not backported to 12.0 (was seen as risky for the GA at the time). 13.0-RC is out now and 13.0-GA is scheduled for release next week.

Best Regards

**Comment by grsmith-projects** [comment]
We updated to v13, and the issue appears to still exist

**Comment by mattlord** [comment]
Hi @grsmith-projects,

We’ve seen a similar but different issue internally too. Can you please open a new issue with all details — or if everything is 100% the same we can reopen this one. But at least internally it was a different cause (different race) with the same high level symptom of a “zombie” tablet in the healthcheck cache.

Thanks!

**Comment by yoheimuta** [comment]
> if everything is 100% the same

Hi @mattlord !

Looks like we're encountering the issue in Vitess 15 in k8s (using vitess-operator):

```SQL
(base) ❯ mysql
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 12823
Server version: 5.7.9-vitess-15.0.1 Version: 15.0.1 (Git revision 13ee9c817638d59bebd6bc598f9d673a893c41cd branch 'heads/v15.0.1') built on Tue Nov 29 21:08:39 UTC 2022 by vitess@buildkitsandbox using go1.18.7 linux/amd64

Copyright (c) 2000, 2022, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show vitess_tablets;
+------------------------+----------+-------+------------+-------------+-----------------------------------+-----------+----------------------+
| Cell                   | Keyspace | Shard | TabletType | State       | Alias                             | Hostname  | PrimaryTermStartTime |
+------------------------+----------+-------+------------+-------------+-----------------------------------+-----------+----------------------+
| asianortheast1a        | main     | -     | PRIMARY    | SERVING     | asianortheast1a-1149099799        | 10.4.7.4  | 2023-01-18T03:06:12Z |
| asianortheast1a        | main     | -     | SPARE      | NOT_SERVING | asianortheast1a-1149099799        | 10.4.4.13 |                      |
| asianortheast1a        | main     | -     | SPARE      | NOT_SERVING | asianortheast1a-3499115096        | 10.4.7.6  |                      |
| asianortheast1areplica | main     | -     | RDONLY     | SERVING     | asianortheast1areplica-2505135016 | 10.4.7.7  |                      |
| asianortheast1areplica | main     | -     | RDONLY     | SERVING     | asianortheast1areplica-3333148644 | 10.4.7.8  |                      |
+------------------------+----------+-------+------------+-------------+-----------------------------------+-----------+----------------------+
5 rows in set (0.04 sec)
```

`10.4.4.13` was shutdown by k8s rolling update, but this line is lingering.
For your reference, I confirmed an inconsistency about `HealthCheck Tablet Cache` among our three vtgate statuses like the following:

<img width="965" alt="image" src="https://user-images.githubusercontent.com/1223268/214224830-3a020bc4-4361-4071-81a2-ce4dee9ba0f7.png">
<img width="709" alt="image" src="https://user-images.githubusercontent.com/1223268/214224849-73c1865b-1a2b-4509-86a8-c2f64fe66cd6.png">
<img width="964" alt="image" src="https://user-images.githubusercontent.com/1223268/214224876-fafc9f68-4af3-4c68-9ca4-4cb7e038c45a.png">

**Comment by mattlord** [comment]
Hi @yoheimuta,

Is it always SPARE tablets in your case? Someone else encountered this issue recently specifically with this tablet type IIRC. I'll start a discussion in the Vitess slack.

Thanks!

**Comment by mantwon** [comment]
We still see this with replica, I originally didn't follow up because it became very low priority... we just restart vtgate if it gets really bad.

on v14.0.3

**Comment by grsmith-projects** [comment]
We still see this with replica, I originally didn't follow up because it became very low priority... we just restart vtgate if it gets really bad.

on v14.0.3

**Comment by yoheimuta** [comment]
@mattlord Yes! we have encountered this issue twice, and it is always with SPARE tablets.
We have never experienced this issue before switching the tablet type from replica to [externalmaster](https://github.com/planetscale/vitess-operator/blob/bfad577802286b9198cfd2b91b1a75d67d037d23/docs/api/index.html#L7035).

**Comment by jwangace** [comment]
Hi, we are running v14.0.x versions, and we see this is happening, worth to mention this usually happens when a Pod goes away and come back after, not always but many occasions.

<img width="698" alt="Screen Shot 2023-06-19 at 11 13 51 AM" src="https://github.com/vitessio/vitess/assets/121262788/87f5d551-1505-4de1-b779-ce6a23e574e6">

**Comment by mattlord** [comment]
@jwangace v14 doesn't have all of the fixes.

**Comment by bluecrabs007** [comment]
@mattlord does v16.0.2 have the fix?
we are seeing this in v16 and trying to see if subsequent versions have it fixed.

**Comment by deepthi** [comment]
#12178 is present in all v16 releases. It's possible that you may need #16371 in addition to that.
